# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.2.0
  # 版权年份
  copyrightYear: 2019
  # 文件上传
  #profile: /home/profile/
  profile: H:\home\profile\
  activity_pfr: http:127.0.0.1:8080/yfg/profile/avatar/
  
   
  #外网映射图片地址
  loadPath: http://59.173.2.76:2132/
  
  #微信API
  appid: wx02d640cfc62a12ce
    #微信appSecret
  appSecret: 329fea0fdd3febb3902b93ada7736d29
    #微信商户号
  wxPaymchId: 1533242691
    #微信支付商户密钥apiKey
  wxPayapiKey: 6c67246d2666450187380b7b0fa05f6e
  
  #微信支付下单地址
  wxPayOrderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  
  #微信支付查询地址
  wxPayQueryUrl: https://api.mch.weixin.qq.com/pay/orderquery
  
  # 获取ip地址开关
  addressEnabled: true
  smstimeout: 60


#小程序相关
  appletsAppId: wx5cb48388719b6a2e
  appletsAppSecret: 866b2b5d2957b8561e4b1d2002698022
  appletsmchId: 1533242691


# 开发环境配置
server:
  # 服务端口
  port: 8080
  servlet:
    # 项目contextPath
     context-path: /yfg
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  level:
    com.yfg: debug
    com.whty: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.yfg,com.whty
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mapper/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/model/*

#fastdfs配置  
fastdFS: 
      url: 10.8.3.231:8887 
fdfs: 
  # 读取时间
  soTimeout: 1501
  # 连接超时时间
  connectTimeout: 691
  # 编码默认UTF-8，charset属性不能自定义
  # charset: UTF-8
  # 缩略图
  thumbImage: 
    # 宽
    width: 150
    # 高
    height: 150
  # tracker列表
  trackerList: 
    10.8.3.231:22122
    
# netty_server
netty: 
  tcp-port: 8092
  boss-count: 1
  worker-count: 10
  keep-alive: true
  backlog: 100
